server:
  port: 8888 #服务端口

spring:
  application:
    name: itcasst-microservice-config-server #指定服务名
  cloud:
    config:
      server:
        git: #配置git仓库地址
          uri: git@github.com:pyygithub/spring-cloud.git
          search-paths: config-server
          username: pyygithub
          password: lang123

eureka:
  client:
    registerWithEureka: true #是否将自己注册到Eureka服务中，默认为true
    fetchRegistry: true #是否从Eureka中获取注册信息，默认为true
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
    ipAddress: 127.0.0.1
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port} #指定实例id
